app:
  mysql:
    enabled: true
    url: root:wufly1217@(127.0.0.1:3306)/go-micro?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100